name: TESTING MERGE
on:
  pull_request:
    branches: 
      - main
      - '*-release'
jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2
      - name: SETUP NODE
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"
      - name: INSTALLING DEPENDENCIES
        run: npm install && cd example && npm install
      - name: BUILDING APPLICATION
        run: npm run build && cd example && npm run build
        id: cibuildstatus
      - name: COMMENT ON PR
        if: ${{ steps.cibuildstatus.outcome }} == "failure"
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          COMMENT_BODY: "{ \"body\": \"PR-RELEASE/BUILD-CHECK - ${{ github.event.pull_request.head.sha }} : ${{ steps.cibuildstatus.outcome }}\" }"
          GITHUB_TOKEN: ${{ secrets.ACTION_KEY }}
        run: |
          echo "$URL"
          echo "Pruning images from failure..."
          docker image prune -f
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "$COMMENT_BODY"
          if [ "${{ steps.cibuildstatus.outcome }}" == "failure" ]
          then
              exit 1
          fi