name: DEPLOYMENT TO GITHUB PAGES
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: INSTALLING DEPENDENCIES
        run: cd example && npm install
      - name: BUILDING APPLICATION
        run: cd example && npm run build
      - name: DEPLOYING TO GH-PAGES
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with: 
          target_branch: gh-pages
          build_dir: example/build
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}